# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 180000 # Goob MRP - 50 Hours, easy to abuse both accidentally and deliberately.
  - !type:CharacterPlaytimeRequirement
    tracker: JobBorg
    min: 54000 # Goob MRP - 15 Hours, you need to know how silicon laws work.
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  nameDataset: NamesAI
  applyTraits: false
  spawnLoadout: false
  canHavePassport: false

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
  canHavePassport: false
